apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU= #base64 encoded, but not encrypted -> not safe!
  mongo-root-password: cGFzc3dvcmQ= #base64 encoded, but not encrypted -> not safe!
