---
- name: Install docker and start docker daemon
  hosts: aws_ec2
  become: yes # Run as root (become_user by default is root)
  tasks:
    - name: Install docker
      ansible.builtin.yum:
        name:
          - docker
        state: present
        update_cache: yes
        allow_downgrade: yes
    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started

- name: Create new linux user
  hosts: all
  become: yes
  tasks:
    - name: Create new linux user
      user:
        name: new-user
        groups: adm,docker


- name: Install docker compose plugin
  hosts: aws_ec2
  become: yes
  become_user: new-user
  tasks:
    - name: set DOCKER_CONFIG environment variable
      ansible.builtin.set_fact:
        DOCKER_CONFIG: /home/new-user/.docker
    - name: Create docker cli plugins directory
      ansible.builtin.file:
        # mkdir -p ~/.docker/cli-plugins
        path: "{{DOCKER_CONFIG}}/cli-plugins"
        state: directory
    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{lookup('pipe', 'uname -m')}}"
        dest: "{{DOCKER_CONFIG}}/cli-plugins/docker-compose"
        mode: +x

- name: Start docker containers
  hosts: aws_ec2
  become: yes
  become_user: new-user
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose file
      ansible.builtin.copy:
        src: /home/kevinp/Documents/openForceDoku/Bildungskarenz23/DevopsBootcamp/github_repo/twn_devops_bootcamp/demo_projects/15_ansible-docker/docker-compose-full.yaml
        dest: /home/new-user/docker-compose.yaml
    - name: Docker login to pull from private registry
      ansible.builtin.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{docker_username}}"
        password: "{{docker_password}}"
    - name: Start container from compose
      community.docker.docker_compose_v2:
        project_src: /home/new-user
        state: present # docker compose up, is default


