---
- name: Install docker and start docker daemon
  hosts: aws_ec2
  become: yes # Run as root (become_user by default is root)
  tasks:
    - name: Install docker
      ansible.builtin.yum:
        name:
          - docker
        state: present
        update_cache: yes
        allow_downgrade: yes
    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started

- name: Create new linux user
  hosts: all
  become: yes
  roles:
    - role: create_user #ansible automatically looks for a role with this name in roles directory

- name: Install docker compose plugin
  hosts: aws_ec2
  become: yes
  become_user: new-user
  tasks:
    - name: set DOCKER_CONFIG environment variable
      ansible.builtin.set_fact:
        DOCKER_CONFIG: /home/new-user/.docker
    - name: Create docker cli plugins directory
      ansible.builtin.file:
        # mkdir -p ~/.docker/cli-plugins
        path: "{{DOCKER_CONFIG}}/cli-plugins"
        state: directory
    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{lookup('pipe', 'uname -m')}}"
        dest: "{{DOCKER_CONFIG}}/cli-plugins/docker-compose"
        mode: +x

- name: Start docker containers
  hosts: aws_ec2
  become: yes
  become_user: new-user
  vars_files:
    - project-vars
  roles:
    - start_containers



