---
- name: Configure nginx web server
  hosts: webserver
  tasks:
    - name: Install nginx server
      apt:
        name: nginx=1.24.0-2ubuntu7
        state: absent
    - name: Start nginx server
      service:
        name: nginx
        state: stopped
