apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
data:
  .dockerconfigjson: BASE64ENCODEDSTRING # replace with the base64 encoded string of the docker config.json file
type: kubernetes.io/dockerconfigjson
